### ISSUE TITLE
Dynamic model instantiation based on user role

### ISSUE THREAD

**Issue by Laurentvw** [Intility/fastapi-azure-auth#104]
I am using models within FastAPI to validate incoming body data. Like so:

```
class Item(BaseModel):
    name: str
    description: Union[str, None] = None
    price: float
    tax: float = 10.5

@app.post("/test")
async def test(item: Item):
    return item
```

The problem is that the model definition should be different based on the Azure user role that's being returned after authentication.

Is there any way to run the azure dependency globally so I can do something like this?

```
# ... start by authenticating right away

if "admin" in user.roles:
  class Item(BaseModel):
      name: str
      description: Union[str, None] = None
      admin_prop: float
else:
  class Item(BaseModel):
      name: str
      description: Union[str, None] = None
      price: float
      non_admin_prop: float = 10.5

# ... routes
```

The correct model needs to be properly loaded on startup so that its schema becomes available in the api docs.

Thank you!
